# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'iOSProver' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOSProver
  pod 'Web3'
  pod 'Web3/PromiseKit'
  pod 'Web3/ContractABI'
  pod 'web3swift.pod' # event fetch
  pod 'QRCodeReader.swift'
end

post_install do |installer|
  # Downgrade Swift language version to 4.0 for Pods that don't support Swift 4.2
  installer.pods_project.targets.each do |target|
    if ['Web3'].include? target.name
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.0'
      end
    end
  end
end
