# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Hopper' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hopper
  # pod 'Web3'
  # pod 'Web3/PromiseKit'
  # pod 'Web3/ContractABI'
  # pod 'web3swift.pod'
  # pod 'QRCodeReader.swift'
end

# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     if ['PromiseKit'].include? target.name
#       target.build_configurations.each do |config|
#         config.build_settings['SWIFT_VERSION'] = '4.2'
#       end
#     end
#   end
# end
